// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLK5S_G0oAM7untHyyEua75dDNDkffH30',
    appId: '1:911799540941:web:54416ecb53f5db63845d84',
    messagingSenderId: '911799540941',
    projectId: 'matchly-app-a09a2',
    authDomain: 'matchly-app-a09a2.firebaseapp.com',
    storageBucket: 'matchly-app-a09a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuy7l8onDYkQZ8Rs7a3YXbZSxwDtzRXQI',
    appId: '1:911799540941:android:28c50638d8e3959d845d84',
    messagingSenderId: '911799540941',
    projectId: 'matchly-app-a09a2',
    storageBucket: 'matchly-app-a09a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD641AQrum1T4Qs8CEFGs8SADdDQ4mqPLQ',
    appId: '1:911799540941:ios:7df8b3fda72f398e845d84',
    messagingSenderId: '911799540941',
    projectId: 'matchly-app-a09a2',
    storageBucket: 'matchly-app-a09a2.firebasestorage.app',
    iosBundleId: 'com.example.matchlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD641AQrum1T4Qs8CEFGs8SADdDQ4mqPLQ',
    appId: '1:911799540941:ios:7df8b3fda72f398e845d84',
    messagingSenderId: '911799540941',
    projectId: 'matchly-app-a09a2',
    storageBucket: 'matchly-app-a09a2.firebasestorage.app',
    iosBundleId: 'com.example.matchlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLK5S_G0oAM7untHyyEua75dDNDkffH30',
    appId: '1:911799540941:web:b8eb60d1354d6ebb845d84',
    messagingSenderId: '911799540941',
    projectId: 'matchly-app-a09a2',
    authDomain: 'matchly-app-a09a2.firebaseapp.com',
    storageBucket: 'matchly-app-a09a2.firebasestorage.app',
  );
}
