"""
Single source of truth for country name translations: English → Turkish.

Used by:
  api_server.py           — builds ALIASES for Turkish search expansion
  gen_dart_countries.py   — generates _trTeam() for the Matchly Flutter app

To add a country: add one line here, then:
  1. Restart api_server  (aliases auto-rebuild on import)
  2. Run gen_dart_countries.py and paste output into add_coupon_sheet.dart
"""

EN_TO_TR: dict[str, str] = {
    # ── A ─────────────────────────────────────────────────────────────────────
    "Afghanistan":              "Afganistan",
    "Albania":                  "Arnavutluk",
    "Algeria":                  "Cezayir",
    "Andorra":                  "Andorra",
    "Angola":                   "Angola",
    "Argentina":                "Arjantin",
    "Armenia":                  "Ermenistan",
    "Australia":                "Avustralya",
    "Austria":                  "Avusturya",
    "Azerbaijan":               "Azerbaycan",
    # ── B ─────────────────────────────────────────────────────────────────────
    "Bahrain":                  "Bahreyn",
    "Belarus":                  "Belarus",
    "Belgium":                  "Belçika",
    "Belize":                   "Belize",
    "Benin":                    "Benin",
    "Bolivia":                  "Bolivya",
    "Bosnia and Herzegovina":   "Bosna Hersek",
    "Bosnia-Herzegovina":       "Bosna Hersek",
    "Botswana":                 "Botsvana",
    "Brazil":                   "Brezilya",
    "Bulgaria":                 "Bulgaristan",
    "Burkina Faso":             "Burkina Faso",
    "Burundi":                  "Burundi",
    # ── C ─────────────────────────────────────────────────────────────────────
    "Cameroon":                 "Kamerun",
    "Canada":                   "Kanada",
    "Cape Verde":               "Yeşil Burun Adaları",
    "Central African Republic": "Orta Afrika Cumhuriyeti",
    "Chad":                     "Çad",
    "Chile":                    "Şili",
    "China":                    "Çin",
    "Colombia":                 "Kolombiya",
    "Comoros":                  "Komorlar",
    "Congo":                    "Kongo",
    "Congo DR":                 "Demokratik Kongo",
    "Costa Rica":               "Kosta Rika",
    "Croatia":                  "Hırvatistan",
    "Cuba":                     "Küba",
    "Curacao":                  "Curaçao",
    "Curaçao":                  "Curaçao",
    "Cyprus":                   "Kıbrıs",
    "Czech Republic":           "Çekya",
    "Czechia":                  "Çekya",
    "Côte d'Ivoire":            "Fildişi Sahili",
    # ── D ─────────────────────────────────────────────────────────────────────
    "Denmark":                  "Danimarka",
    "Djibouti":                 "Cibuti",
    "Dominican Republic":       "Dominik Cumhuriyeti",
    "DR Congo":                 "Demokratik Kongo",
    # ── E ─────────────────────────────────────────────────────────────────────
    "Ecuador":                  "Ekvador",
    "Egypt":                    "Mısır",
    "El Salvador":              "El Salvador",
    "England":                  "İngiltere",
    "Equatorial Guinea":        "Ekvator Ginesi",
    "Eritrea":                  "Eritre",
    "Estonia":                  "Estonya",
    "Eswatini":                 "Esvatini",
    "Ethiopia":                 "Etiyopya",
    # ── F ─────────────────────────────────────────────────────────────────────
    "Faroe Islands":            "Faroe Adaları",
    "Fiji":                     "Fiji",
    "Finland":                  "Finlandiya",
    "France":                   "Fransa",
    # ── G ─────────────────────────────────────────────────────────────────────
    "Gabon":                    "Gabon",
    "Gambia":                   "Gambiya",
    "Georgia":                  "Gürcistan",
    "Germany":                  "Almanya",
    "Ghana":                    "Gana",
    "Gibraltar":                "Cebelitarık",
    "Greece":                   "Yunanistan",
    "Guatemala":                "Guatemala",
    "Guinea":                   "Gine",
    "Guinea-Bissau":            "Gine-Bissau",
    "Guyana":                   "Guyana",
    # ── H ─────────────────────────────────────────────────────────────────────
    "Haiti":                    "Haiti",
    "Honduras":                 "Honduras",
    "Hungary":                  "Macaristan",
    # ── I ─────────────────────────────────────────────────────────────────────
    "Iceland":                  "İzlanda",
    "India":                    "Hindistan",
    "Indonesia":                "Endonezya",
    "Iran":                     "İran",
    "Iraq":                     "Irak",
    "Ireland":                  "İrlanda",
    "Israel":                   "İsrail",
    "Italy":                    "İtalya",
    "Ivory Coast":              "Fildişi Sahili",
    # ── J ─────────────────────────────────────────────────────────────────────
    "Jamaica":                  "Jamaika",
    "Japan":                    "Japonya",
    "Jordan":                   "Ürdün",
    # ── K ─────────────────────────────────────────────────────────────────────
    "Kazakhstan":               "Kazakistan",
    "Kenya":                    "Kenya",
    "Korea Republic":           "Güney Kore",
    "Kosovo":                   "Kosova",
    "Kuwait":                   "Kuveyt",
    # ── L ─────────────────────────────────────────────────────────────────────
    "Latvia":                   "Letonya",
    "Lebanon":                  "Lübnan",
    "Lesotho":                  "Lesoto",
    "Liberia":                  "Liberya",
    "Libya":                    "Libya",
    "Liechtenstein":            "Lihtenştayn",
    "Lithuania":                "Litvanya",
    "Luxembourg":               "Lüksemburg",
    # ── M ─────────────────────────────────────────────────────────────────────
    "Madagascar":               "Madagaskar",
    "Malawi":                   "Malavi",
    "Malaysia":                 "Malezya",
    "Mali":                     "Mali",
    "Malta":                    "Malta",
    "Mauritania":               "Moritanya",
    "Mauritius":                "Mauritius",
    "Mexico":                   "Meksika",
    "Moldova":                  "Moldova",
    "Montenegro":               "Karadağ",
    "Morocco":                  "Fas",
    "Mozambique":               "Mozambik",
    "Myanmar":                  "Myanmar",
    # ── N ─────────────────────────────────────────────────────────────────────
    "Namibia":                  "Namibya",
    "Netherlands":              "Hollanda",
    "New Zealand":              "Yeni Zelanda",
    "Nicaragua":                "Nikaragua",
    "Niger":                    "Nijer",
    "Nigeria":                  "Nijerya",
    "North Macedonia":          "Kuzey Makedonya",
    "Northern Ireland":         "Kuzey İrlanda",
    "Norway":                   "Norveç",
    # ── O ─────────────────────────────────────────────────────────────────────
    "Oman":                     "Umman",
    # ── P ─────────────────────────────────────────────────────────────────────
    "Pakistan":                 "Pakistan",
    "Palestine":                "Filistin",
    "Panama":                   "Panama",
    "Papua New Guinea":         "Papua Yeni Gine",
    "Paraguay":                 "Paraguay",
    "Peru":                     "Peru",
    "Philippines":              "Filipinler",
    "Poland":                   "Polonya",
    "Portugal":                 "Portekiz",
    # ── Q ─────────────────────────────────────────────────────────────────────
    "Qatar":                    "Katar",
    # ── R ─────────────────────────────────────────────────────────────────────
    "Romania":                  "Romanya",
    "Russia":                   "Rusya",
    "Rwanda":                   "Ruanda",
    # ── S ─────────────────────────────────────────────────────────────────────
    "San Marino":               "San Marino",
    "Saudi Arabia":             "Suudi Arabistan",
    "Scotland":                 "İskoçya",
    "Senegal":                  "Senegal",
    "Serbia":                   "Sırbistan",
    "Seychelles":               "Seyşeller",
    "Sierra Leone":             "Sierra Leone",
    "Slovakia":                 "Slovakya",
    "Slovenia":                 "Slovenya",
    "Somalia":                  "Somali",
    "South Africa":             "Güney Afrika",
    "South Korea":              "Güney Kore",
    "South Sudan":              "Güney Sudan",
    "Spain":                    "İspanya",
    "Sudan":                    "Sudan",
    "Suriname":                 "Surinam",
    "Sweden":                   "İsveç",
    "Switzerland":              "İsviçre",
    "Syria":                    "Suriye",
    # ── T ─────────────────────────────────────────────────────────────────────
    "Tanzania":                 "Tanzanya",
    "Thailand":                 "Tayland",
    "Togo":                     "Togo",
    "Trinidad and Tobago":      "Trinidad ve Tobago",
    "Tunisia":                  "Tunus",
    "Turkey":                   "Türkiye",
    # ── U ─────────────────────────────────────────────────────────────────────
    "UAE":                      "Birleşik Arap Emirlikleri",
    "Uganda":                   "Uganda",
    "Ukraine":                  "Ukrayna",
    "United Arab Emirates":     "Birleşik Arap Emirlikleri",
    "United States":            "Amerika Birleşik Devletleri",
    "Uruguay":                  "Uruguay",
    "USA":                      "Amerika Birleşik Devletleri",
    "Uzbekistan":               "Özbekistan",
    # ── V ─────────────────────────────────────────────────────────────────────
    "Venezuela":                "Venezuela",
    "Vietnam":                  "Vietnam",
    # ── W ─────────────────────────────────────────────────────────────────────
    "Wales":                    "Galler",
    # ── Y ─────────────────────────────────────────────────────────────────────
    "Yemen":                    "Yemen",
    # ── Z ─────────────────────────────────────────────────────────────────────
    "Zambia":                   "Zambiya",
    "Zimbabwe":                 "Zimbabwe",
}
