"""
Patches ALIASES dict in /opt/KuponBot/api_server.py to add full Turkish search support.
Run on VPS:
  python3 /opt/KuponBot/patch_aliases.py
"""

import pathlib, sys, re

TARGET = pathlib.Path("/opt/KuponBot/api_server.py")
src = TARGET.read_text()

NEW_ALIASES = '''\
ALIASES: dict[str, list[str]] = {
    # ── National teams (TR → EN + variants) ──────────────────────────────────
    "türkiye":                    ["turkey", "türkiye", "turkiye"],
    "turkiye":                    ["turkey", "türkiye", "turkiye"],
    "turkey":                     ["turkey", "türkiye", "turkiye"],
    "amerika birleşik devletleri":["united states", "usa", "us"],
    "amerika birlesiK devletleri":["united states", "usa", "us"],
    "amerika":                    ["united states", "usa", "us"],
    "abd":                        ["united states", "usa", "us"],
    "united states":              ["united states", "usa", "us"],
    "usa":                        ["united states", "usa", "us"],
    "ingiltere":                  ["england", "ingiltere"],
    "england":                    ["england"],
    "almanya":                    ["germany", "deutschland", "almanya"],
    "germany":                    ["germany", "deutschland"],
    "fransa":                     ["france", "fransa"],
    "france":                     ["france"],
    "ispanya":                    ["spain", "españa", "espana", "ispanya"],
    "spain":                      ["spain", "españa", "espana"],
    "italya":                     ["italy", "italia", "italya"],
    "italy":                      ["italy", "italia"],
    "hollanda":                   ["netherlands", "holland", "hollanda"],
    "netherlands":                ["netherlands", "holland"],
    "belçika":                    ["belgium", "belçika", "belcika"],
    "belcika":                    ["belgium", "belçika", "belcika"],
    "belgium":                    ["belgium"],
    "portekiz":                   ["portugal", "portekiz"],
    "portugal":                   ["portugal"],
    "brezilya":                   ["brazil", "brasil", "brezilya"],
    "brazil":                     ["brazil", "brasil"],
    "arjantin":                   ["argentina", "arjantin"],
    "argentina":                  ["argentina"],
    "avustralya":                 ["australia", "avustralya"],
    "australia":                  ["australia"],
    "kanada":                     ["canada", "kanada"],
    "canada":                     ["canada"],
    "isviçre":                    ["switzerland", "isviçre", "isvicre"],
    "isvicre":                    ["switzerland", "isviçre", "isvicre"],
    "switzerland":                ["switzerland"],
    "norveç":                     ["norway", "norveç", "norvec"],
    "norvec":                     ["norway", "norveç", "norvec"],
    "norway":                     ["norway"],
    "isveç":                      ["sweden", "isveç", "isvec"],
    "isvec":                      ["sweden", "isveç", "isvec"],
    "sweden":                     ["sweden"],
    "japonya":                    ["japan", "japonya"],
    "japan":                      ["japan"],
    "güney kore":                 ["south korea", "güney kore", "guney kore"],
    "guney kore":                 ["south korea", "güney kore", "guney kore"],
    "kore":                       ["korea", "south korea"],
    "south korea":                ["south korea"],
    "meksika":                    ["mexico", "meksika"],
    "mexico":                     ["mexico"],
    "fas":                        ["morocco", "fas"],
    "morocco":                    ["morocco"],
    "iskoçya":                    ["scotland", "iskoçya", "iskocya"],
    "iskocya":                    ["scotland", "iskoçya", "iskocya"],
    "scotland":                   ["scotland"],
    "uruguay":                    ["uruguay"],
    "kolombiya":                  ["colombia", "kolombiya"],
    "colombia":                   ["colombia"],
    "hırvatistan":                ["croatia", "hrvatska", "hırvatistan", "hirvatistan"],
    "hirvatistan":                ["croatia", "hrvatska", "hırvatistan", "hirvatistan"],
    "croatia":                    ["croatia", "hrvatska"],
    "gana":                       ["ghana", "gana"],
    "ghana":                      ["ghana"],
    "panama":                     ["panama"],
    "avusturya":                  ["austria", "avusturya"],
    "austria":                    ["austria"],
    "cezayir":                    ["algeria", "cezayir"],
    "algeria":                    ["algeria"],
    "ürdün":                      ["jordan", "ürdün", "urdun"],
    "urdun":                      ["jordan", "ürdün", "urdun"],
    "jordan":                     ["jordan"],
    "ırak":                       ["iraq", "ırak", "irak"],
    "irak":                       ["iraq", "ırak", "irak"],
    "iraq":                       ["iraq"],
    "senegal":                    ["senegal"],
    "tunus":                      ["tunisia", "tunus"],
    "tunisia":                    ["tunisia"],
    "mısır":                      ["egypt", "mısır", "misir"],
    "misir":                      ["egypt", "mısır", "misir"],
    "egypt":                      ["egypt"],
    "iran":                       ["iran"],
    "yeni zelanda":               ["new zealand", "yeni zelanda"],
    "new zealand":                ["new zealand"],
    "katar":                      ["qatar", "katar"],
    "qatar":                      ["qatar"],
    "suudi arabistan":            ["saudi arabia", "suudi arabistan"],
    "saudi arabia":               ["saudi arabia"],
    "çekya":                      ["czechia", "czech", "çekya", "cekya"],
    "cekya":                      ["czechia", "czech", "çekya", "cekya"],
    "czechia":                    ["czechia", "czech"],
    "güney afrika":               ["south africa", "güney afrika", "guney afrika"],
    "guney afrika":               ["south africa", "güney afrika", "guney afrika"],
    "south africa":               ["south africa"],
    "bosna hersek":               ["bosnia", "bosnia-herzegovina", "bosnia and herzegovina"],
    "bosna-hersek":               ["bosnia", "bosnia-herzegovina", "bosnia and herzegovina"],
    "bosnia-herzegovina":         ["bosnia", "bosnia-herzegovina", "bosnia and herzegovina"],
    "fildişi sahili":             ["ivory coast", "côte d\'ivoire", "cote d\'ivoire"],
    "fildisi sahili":             ["ivory coast", "côte d\'ivoire", "cote d\'ivoire"],
    "ivory coast":                ["ivory coast", "côte d\'ivoire"],
    "ekvador":                    ["ecuador", "ekvador"],
    "ecuador":                    ["ecuador"],
    "curaçao":                    ["curaçao", "curacao"],
    "curacao":                    ["curaçao", "curacao"],
    "demokratik kongo":           ["congo dr", "dr congo", "democratic congo"],
    "congo dr":                   ["congo dr", "dr congo"],
    "dr congo":                   ["congo dr", "dr congo"],
    "özbekistan":                 ["uzbekistan", "özbekistan", "ozbekistan"],
    "ozbekistan":                 ["uzbekistan", "özbekistan", "ozbekistan"],
    "uzbekistan":                 ["uzbekistan"],
    "yeşil burun adaları":        ["cape verde", "yeşil burun adaları"],
    "yesil burun adalari":        ["cape verde", "yeşil burun adaları"],
    "cape verde":                 ["cape verde"],
    "haiti":                      ["haiti"],
    "paraguay":                   ["paraguay"],
    # ── Turkish clubs ─────────────────────────────────────────────────────────
    "galatasaray":                ["galatasaray"],
    "gs":                         ["galatasaray"],
    "fenerbahce":                 ["fenerbahce", "fenerbahçe"],
    "fenerbahçe":                 ["fenerbahce", "fenerbahçe"],
    "fb":                         ["fenerbahce", "fenerbahçe"],
    "besiktas":                   ["besiktas", "beşiktaş"],
    "beşiktaş":                   ["besiktas", "beşiktaş"],
    "bjk":                        ["besiktas", "beşiktaş"],
    "trabzonspor":                ["trabzonspor"],
    "trabzon":                    ["trabzonspor"],
    "trb":                        ["trabzonspor"],
    "basaksehir":                 ["basaksehir", "başakşehir", "istanbul basaksehir"],
    "başakşehir":                 ["basaksehir", "başakşehir", "istanbul basaksehir"],
    "antalyaspor":                ["antalyaspor"],
    "sivasspor":                  ["sivasspor"],
    "kasimpasa":                  ["kasimpasa", "kasımpaşa"],
    "kasımpaşa":                  ["kasimpasa", "kasımpaşa"],
    # ── Leagues ───────────────────────────────────────────────────────────────
    "sampiyonlar ligi":           ["champions league", "şampiyonlar ligi", "ucl"],
    "şampiyonlar ligi":           ["champions league", "şampiyonlar ligi", "ucl"],
    "ucl":                        ["champions league", "şampiyonlar ligi"],
    "premier lig":                ["premier league"],
    "premier league":             ["premier league"],
    "la liga":                    ["la liga", "laliga"],
    "laliga":                     ["la liga", "laliga"],
    "seri a":                     ["serie a"],
    "serie a":                    ["serie a"],
    "bundesliga":                 ["bundesliga"],
    "ligue 1":                    ["ligue 1"],
    "super lig":                  ["super lig", "süper lig"],
    "süper lig":                  ["super lig", "süper lig"],
    "europa league":              ["europa league", "uel"],
    "uel":                        ["europa league", "uel"],
    "dunya kupasi":               ["world cup", "dünya kupası", "fifa world cup"],
    "dünya kupası":               ["world cup", "dünya kupası", "fifa world cup"],
    "world cup":                  ["world cup", "dünya kupası", "fifa world cup"],
}'''

# Replace the entire ALIASES block (from "ALIASES: dict" up to the closing "}")
pattern = re.compile(r'ALIASES: dict\[str, list\[str\]\] = \{.*?\}', re.DOTALL)
if not pattern.search(src):
    sys.exit("ERROR: ALIASES block not found — check manually.")

patched = pattern.sub(NEW_ALIASES, src, count=1)
TARGET.write_text(patched, encoding="utf-8")
print("ALIASES patched OK.")
print("Restart: systemctl restart matchly-api")
print("Verify:  curl 'http://localhost:8001/api/matches/search?q=amerika'")
print("Verify:  curl 'http://localhost:8001/api/matches/search?q=güney+kore'")
